project:
  type: website

website:
  title: "WX's Blog"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
        icon: house
      - text: "About"
        href: about.qmd
        icon: person-circle
      - text: "Work"
        href: work.qmd
        icon: briefcase
      - text: "Blog"
        href: blog.qmd
        icon: pencil-square
    right:
      - icon: github
        href: https://github.com/ZephyrXiao7
      - icon: envelope
        href: mailto:wenxin_xiao@g.harvard.edu

  page-footer:
    left: 
      - text: " 2025 Wenxin Xiao. All rights reserved."
    center:
      - text: "Made with"
      - icon: heart-fill
        href: https://quarto.org
      - text: "and Quarto"
    right: 
      - icon: github
        href: https://github.com/ZephyrXiao7
      - icon: envelope
        href: mailto:wenxin_xiao@g.harvard.edu
      - icon: film
        text: "Blue Bird"
        href: https://liz-bluebird.com/
    background: light
    border: true

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
